//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Codigo_Transporte_Aereo
    {
        public int id_codigo_transporte_aereo { get; set; }
        public string clave_identificacion { get; set; }
        public string nacionalidad { get; set; }
        public string nombre_aerolinea { get; set; }
        public string designador_OACI { get; set; }
    }
}
