//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Ferroviarios
    {
        public int id_ferroviario { get; set; }
        public int id_usuario { get; set; }
        public string rfc_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<byte> id_estatus { get; set; }
        public Nullable<int> id_derecho { get; set; }
        public Nullable<decimal> km_pagado { get; set; }
        public string tipo_carro { get; set; }
        public string matricula_carro { get; set; }
        public string guia_carro { get; set; }
        public string tipo_contenedor { get; set; }
        public Nullable<int> peso_contenedor_vacio { get; set; }
        public Nullable<int> peso_neto_mercancia { get; set; }
    }
}
