//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Grupos_Empleados
    {
        public int id_grupo_empleados { get; set; }
        public string grupo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario { get; set; }
        public string rfc_usuario { get; set; }
        public string estado { get; set; }
        public string registro_patronal { get; set; }
    }
}
