//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Usuarios
    {
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public int id_perfil { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_estatus { get; set; }
        public string url_imagen { get; set; }
        public string rfc { get; set; }
        public string nombre_razon { get; set; }
        public int id_tipo_persona { get; set; }
        public int id_regimen_fiscal { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public string cp { get; set; }
        public string calle { get; set; }
        public string num_ext { get; set; }
        public string num_int { get; set; }
        public string colonia { get; set; }
        public string localidad { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string registro_patronal { get; set; }
    }
}
