//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Ubicaciones
    {
        public int id_ubicacion { get; set; }
        public int id_usuario { get; set; }
        public string rfc_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_estatus { get; set; }
        public string nombre_ubicacion { get; set; }
        public string id_origen_destino { get; set; }
        public string rfc_origen_destino { get; set; }
        public string nombre_origen_destino { get; set; }
        public string pais { get; set; }
        public string codigo_postal { get; set; }
        public string calle { get; set; }
        public string num_ext { get; set; }
        public string num_int { get; set; }
        public string colonia { get; set; }
        public string localidad { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string referencia { get; set; }
        public int id_tipo_ubicacion { get; set; }
    }
}
