//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Clientes
    {
        public int id_cliente { get; set; }
        public string nombre_razon { get; set; }
        public string rfc { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string direccion_fiscal { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_uso_cdfi { get; set; }
        public string rfc_usuario { get; set; }
        public int id_estatus { get; set; }
        public Nullable<int> id_regimen_fiscal { get; set; }
        public Nullable<int> codigo_postal { get; set; }
    }
}
