//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Paquetes
    {
        public int id_paquete { get; set; }
        public string nombre_paquete { get; set; }
        public string descripcion_paquete { get; set; }
        public int folios { get; set; }
        public decimal costo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_estatus { get; set; }
        public decimal importe { get; set; }
        public decimal iva { get; set; }
        public decimal comision { get; set; }
    }
}
