//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Config_AutoTransporte
    {
        public int id_conf_autotrans { get; set; }
        public string clave { get; set; }
        public string descripcion { get; set; }
        public string num_eje { get; set; }
        public string num_llantas { get; set; }
        public int estatus { get; set; }
    }
}
