//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Unidades_Peso
    {
        public int id_unidad_peso { get; set; }
        public string clave_unidad { get; set; }
        public string nombre__unidad_peso { get; set; }
        public string descripcion { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> fecha_inicio_vigencia { get; set; }
        public Nullable<System.DateTime> fecha_fin_vigencia { get; set; }
        public string simbolo { get; set; }
        public string bandera { get; set; }
    }
}
