//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Derecho_Paso
    {
        public int id_derecho_paso { get; set; }
        public string clave_derecho_paso { get; set; }
        public string derecho_paso { get; set; }
        public string entre { get; set; }
        public string hasta { get; set; }
        public string otorga_recibe { get; set; }
        public string concesionario { get; set; }
        public Nullable<int> status { get; set; }
    }
}
