//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Empleados
    {
        public int id_empleado { get; set; }
        public int id_grupo_empleados { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string curp { get; set; }
        public string nss { get; set; }
        public System.DateTime inicio_relacion_laboral { get; set; }
        public string rfc { get; set; }
        public decimal salario_diario_integrado { get; set; }
        public decimal salario_diario_cuotas_apoprtaciones { get; set; }
        public int id_tipo_contrato { get; set; }
        public int id_regimen_contratacion { get; set; }
        public int id_riesgo_puesto { get; set; }
        public int id_tipo_jornada { get; set; }
        public int id_periodicidad_pago { get; set; }
        public string num_empleado { get; set; }
        public string puesto { get; set; }
        public string departamento { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public string cp { get; set; }
        public string calle { get; set; }
        public string num_ext { get; set; }
        public string num_int { get; set; }
        public string colonia { get; set; }
        public string localidad { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario { get; set; }
        public int id_estatus { get; set; }
        public string rfc_usuario { get; set; }
    }
}
