//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Pre_Carta_Porte
    {
        public int id { get; set; }
        public int id_cfdi { get; set; }
        public int id_emisor { get; set; }
        public int id_receptor { get; set; }
        public int id_prefactura { get; set; }
        public int id_mercancia { get; set; }
        public int id_figura { get; set; }
        public Nullable<int> id_autotransporte { get; set; }
        public string transporte_inter { get; set; }
        public string e_s_mercancia { get; set; }
        public string pais_ori_des { get; set; }
        public string total_distancia_rec { get; set; }
        public string tipo_figura { get; set; }
        public string res_fiscal_figura { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string status { get; set; }
        public string url_xml { get; set; }
        public string url_pdf { get; set; }
    }
}
