//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Solicitudes_Descarga
    {
        public int id_solicitud_descarga { get; set; }
        public string TipoDescarga { get; set; }
        public int EstadoDescargaEmisor { get; set; }
        public int EstadoDescargaReceptor { get; set; }
        public int CodigoEstadoSolicitudEmisor { get; set; }
        public int CodigoEstadoSolicitudReceptor { get; set; }
        public int NumVerificacionesEjecutadasEmisor { get; set; }
        public int NumVerificacionesEjecutadasReceptor { get; set; }
        public string MensajeSATDescargaEmisor { get; set; }
        public string MensajeSATDescargaReceptor { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string RFCReceptor { get; set; }
        public string RFCEmisor { get; set; }
        public string IdSolicitudCFDIRecibidos { get; set; }
        public string IdSolicitudCFDIEmitidos { get; set; }
        public string PackageID { get; set; }
        public string Token { get; set; }
        public System.DateTime FechaVerificacionEmisor { get; set; }
        public System.DateTime FechaVerificacionReceptor { get; set; }
    }
}
