//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Facturas
    {
        public int id_factura { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public decimal tipo_cambio { get; set; }
        public string serie { get; set; }
        public string folio { get; set; }
        public string lugar_expedicion { get; set; }
        public string exportacion { get; set; }
        public string moneda { get; set; }
        public decimal total_original { get; set; }
        public decimal subtotal { get; set; }
        public int id_tipo_comprobante { get; set; }
        public int id_forma_pago { get; set; }
        public int id_metodo_pago { get; set; }
        public decimal descuento { get; set; }
        public decimal total { get; set; }
        public string uuid { get; set; }
        public string rfc_emisor { get; set; }
        public string nombre_emisor { get; set; }
        public int id_regimen_fiscal_emisor { get; set; }
        public string rfc_receptor { get; set; }
        public string nombre_receptor { get; set; }
        public int id_uso_cfdi { get; set; }
        public int id_regimen_fiscal_receptor { get; set; }
        public string domicio_fiscal_receptor { get; set; }
        public System.DateTime fecha_timbrado { get; set; }
        public string version_cfdi { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string url_xml { get; set; }
        public int id_estatus { get; set; }
        public System.DateTime fecha_validacion { get; set; }
        public string certificado_sat { get; set; }
        public string sello_cfdi { get; set; }
        public string sello_sat { get; set; }
    }
}
