//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Carta_Porte
    {
        public int id_carta_porte { get; set; }
        public int id_factura { get; set; }
        public int id_autotransporte { get; set; }
        public string trans_inter { get; set; }
        public decimal total_dist_rec { get; set; }
        public string id_origen { get; set; }
        public string rfc_origen { get; set; }
        public string nombre_razon_origen { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public string direccion_origen { get; set; }
        public string id_destino { get; set; }
        public string rfc_destino { get; set; }
        public string nombre_razon_destino { get; set; }
        public decimal distancia_recorrida { get; set; }
        public System.DateTime fecha_llegada { get; set; }
        public string direccion_destino { get; set; }
        public decimal peso_bruto { get; set; }
        public string unidad_peso { get; set; }
        public string num_mercancias { get; set; }
        public string bienes_trans { get; set; }
        public string descripcion { get; set; }
        public decimal cantidad { get; set; }
        public string clave_unidad { get; set; }
        public string unidad { get; set; }
        public decimal peso_kg { get; set; }
        public string permiso_sct { get; set; }
        public string num_permiso_sct { get; set; }
        public string config_vehicular { get; set; }
        public string placa { get; set; }
        public string modelo { get; set; }
        public string asegura_resp_civil { get; set; }
        public string poliza_resp_civil { get; set; }
        public string sub_tipo_remolque { get; set; }
        public string placa_remolque { get; set; }
        public string tipo_figura { get; set; }
        public string rfc_figura { get; set; }
        public string num_licencia { get; set; }
        public string nomnre_figura { get; set; }
        public string url_pdf { get; set; }
    }
}
