//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Cancelacion_Factura
    {
        public int id { get; set; }
        public int id_pre_fac { get; set; }
        public string rfc_emisor { get; set; }
        public string rfc_receptor { get; set; }
        public string uuid { get; set; }
        public string folio_sustitucion { get; set; }
        public string motivo { get; set; }
        public string acuse { get; set; }
        public string fecha { get; set; }
        public string estatus_camcelacion { get; set; }
        public string estatus_uuid { get; set; }
    }
}
