//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Pagos_Nota_Venta
    {
        public int id_pago_nota { get; set; }
        public int id_nota_venta { get; set; }
        public int id_forma_pago { get; set; }
        public string tipo_pago { get; set; }
        public decimal total_pagado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario { get; set; }
        public string rfc_usuario { get; set; }
        public string url_comprobante { get; set; }
        public int id_uso_cfdi { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public int id_estatus { get; set; }
    }
}
