//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Detalle_Prepago
    {
        public int id { get; set; }
        public int id_pre_pago { get; set; }
        public string uuid { get; set; }
        public Nullable<int> forma_pago { get; set; }
        public Nullable<int> num_pago { get; set; }
        public Nullable<decimal> s_anterior { get; set; }
        public Nullable<decimal> pago { get; set; }
        public Nullable<decimal> s_actual { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
