//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Notas_Venta
    {
        public int id_nota_venta { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string clave_nota { get; set; }
        public decimal subtotal { get; set; }
        public decimal iva { get; set; }
        public decimal ieps { get; set; }
        public decimal iva_ret { get; set; }
        public decimal isr_ret { get; set; }
        public decimal descuento { get; set; }
        public decimal total { get; set; }
        public int id_estatus { get; set; }
        public string url_pdf { get; set; }
        public string url_xml { get; set; }
        public string folio { get; set; }
        public string serie { get; set; }
        public string rfc_usuario { get; set; }
        public int id_cuenta_bancaria { get; set; }
        public Nullable<int> id_forma_pago { get; set; }
        public Nullable<int> id_metodo_pago { get; set; }
        public string lugar_expedicion { get; set; }
        public Nullable<int> id_uso_cfdi { get; set; }
        public string uuid { get; set; }
    }
}
