//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Envios_Correo_Nota
    {
        public int id_envio_correo_nota { get; set; }
        public int id_nota_venta { get; set; }
        public int id_usuario { get; set; }
        public int id_cliente { get; set; }
        public string rfc_usuario { get; set; }
        public bool enviado { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha_enviado { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
    }
}
