//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Conceptos_Nota_Venta
    {
        public int id_detalle_nota_venta { get; set; }
        public int id_nota_venta { get; set; }
        public int id_sat { get; set; }
        public string clave { get; set; }
        public int id_unidad_medida { get; set; }
        public decimal precio_unitario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario { get; set; }
        public int id_iva { get; set; }
        public int id_iva_ret { get; set; }
        public int id_isr { get; set; }
        public int id_ieps { get; set; }
        public int es_tasa_ieps { get; set; }
        public decimal cuota_ieps { get; set; }
        public int tipo_descuento { get; set; }
        public decimal descuento { get; set; }
        public decimal total_descuento { get; set; }
        public decimal importe { get; set; }
        public decimal total { get; set; }
        public decimal cantidad { get; set; }
        public decimal total_iva { get; set; }
        public decimal total_iva_ret { get; set; }
        public decimal total_isr_ret { get; set; }
        public string concepto { get; set; }
        public string rfc_usuario { get; set; }
    }
}
