//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Cobros
    {
        public int id_cobro { get; set; }
        public int id_usuario { get; set; }
        public int id_paquete { get; set; }
        public string id_preference { get; set; }
        public int id_uso_cfdi { get; set; }
        public int id_forma_pago { get; set; }
        public System.DateTime fecha_cobro { get; set; }
        public decimal importe { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public int id_estatus { get; set; }
        public string correo_electronico { get; set; }
        public string payment_id { get; set; }
        public string payment_method { get; set; }
        public string status { get; set; }
        public int id_vendedor_usuario { get; set; }
        public int timbres { get; set; }
        public decimal comision { get; set; }
        public string init_point { get; set; }
        public string rfc_usuario { get; set; }
        public string lugar_expedicion { get; set; }
        public string url_xml { get; set; }
        public string url_pdf { get; set; }
        public string uuid { get; set; }
    }
}
