//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Cfdi_Uuid
    {
        public int id_cfdi_pre_factura { get; set; }
        public int id_pre_factura { get; set; }
        public string id_relacion { get; set; }
        public string uuid { get; set; }
    }
}
