//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Pre_Pagos
    {
        public int id { get; set; }
        public int id_pre_factura { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> metodo_pago { get; set; }
        public Nullable<int> uso_cfdi { get; set; }
        public string serie { get; set; }
        public string folio { get; set; }
        public Nullable<int> num_operacion { get; set; }
        public Nullable<int> tipo_moneda { get; set; }
        public string tipo_cambio { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string hora { get; set; }
        public Nullable<decimal> total { get; set; }
        public string uuid { get; set; }
        public string url_pdf { get; set; }
        public string url_xml { get; set; }
        public string selloCFDI { get; set; }
        public string selloSAT { get; set; }
        public string ccertificacion { get; set; }
        public string version_cfdi { get; set; }
        public string version_timbrado { get; set; }
        public Nullable<System.DateTime> fca_timbrado { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
