//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Transporte_Aereo
    {
        public int id_transporte_aereo { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public int id_tipo_permiso { get; set; }
        public string num_permiso_sct { get; set; }
        public string matricula_aeronave { get; set; }
        public string nombre_aseg { get; set; }
        public string num_poliza_seguro { get; set; }
        public string numero_guia { get; set; }
        public string lugar_contrato { get; set; }
        public string rfc_transportista { get; set; }
        public int id_codigo_transporte_aereo { get; set; }
        public string num_reg_id_trib_transpor { get; set; }
        public Nullable<int> id_pais_transpor { get; set; }
        public string nombre_transportista { get; set; }
        public string rfc_embarcador { get; set; }
        public string num_reg_id_trib_embarc { get; set; }
        public Nullable<int> id_pais_embarc { get; set; }
        public string nombre_embarcador { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
