//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Transporte_Maritimo
    {
        public int id_transporte_maritimo { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> permiso_sct { get; set; }
        public string num_permiso_sct { get; set; }
        public string nombre_aseg { get; set; }
        public string num_poliza_seguro { get; set; }
        public int tipo_embarcacion { get; set; }
        public string matricula { get; set; }
        public string numero_omi { get; set; }
        public Nullable<int> anio_embarcacion { get; set; }
        public string nombre_embarcacion { get; set; }
        public int nacionalidad_embarcacion { get; set; }
        public decimal unidades_arq_bruto { get; set; }
        public int tipo_carga { get; set; }
        public string num_cert_itc { get; set; }
        public Nullable<decimal> eslora { get; set; }
        public Nullable<decimal> manga { get; set; }
        public Nullable<decimal> calado { get; set; }
        public string linea_naviera { get; set; }
        public string nombre_agente_naviero { get; set; }
        public int num_autorizacion_naviero { get; set; }
        public string num_viaje { get; set; }
        public string num_conoc_embarc { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
