//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Autotransporte
    {
        public int id_autotransporte { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public int id_tipo_permiso { get; set; }
        public string num_permiso_sct { get; set; }
        public int id_conf_autotrans { get; set; }
        public string placa_vm { get; set; }
        public int anio_modelo_vm { get; set; }
        public string asegura_resp_civil { get; set; }
        public string poliza_resp_civil { get; set; }
        public string asegura_med_ambiente { get; set; }
        public string poliza_med_ambiente { get; set; }
        public string asegura_carga { get; set; }
        public string poliza_carga { get; set; }
        public Nullable<decimal> prima_seguro { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
