//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Conceptos_Pre_Factura
    {
        public int id_concepto_pre_factura { get; set; }
        public int id_pre_factura { get; set; }
        public int id_sat { get; set; }
        public string c_prod_serv { get; set; }
        public string c_producto { get; set; }
        public string cantidad { get; set; }
        public string c_unidad_medida { get; set; }
        public string unidad { get; set; }
        public string concepto { get; set; }
        public string importe_unitario { get; set; }
        public string importe_total { get; set; }
        public string descuento { get; set; }
        public string obj_impuesto { get; set; }
        public string iva_imp_traslado { get; set; }
        public string tipo_factor { get; set; }
        public string iva_tasa { get; set; }
        public string iva_tasa_impuesto { get; set; }
        public string iva_ret { get; set; }
        public string iva_ret_tasa { get; set; }
        public string iva_ret_impuesto { get; set; }
        public string isr_ret { get; set; }
        public string isr_ret_tasa { get; set; }
        public string isr_ret_impuesto { get; set; }
        public string tipo_ieps { get; set; }
        public string ieps { get; set; }
        public string v_ieps { get; set; }
        public string total { get; set; }
        public string total_imp_retenido { get; set; }
    }
}
