//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Figuras
    {
        public int id_figura { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_figura_transporte { get; set; }
        public string rfc_figura { get; set; }
        public string num_licencia { get; set; }
        public string nombre_figura { get; set; }
        public string num_reg_id_trib_figura { get; set; }
        public Nullable<int> residencia_fiscal_id_pais { get; set; }
        public Nullable<int> id_partes_transporte { get; set; }
        public string calle { get; set; }
        public Nullable<int> num_exterior { get; set; }
        public Nullable<int> num_interiror { get; set; }
        public string colonia { get; set; }
        public Nullable<int> id_localidad { get; set; }
        public string referencia { get; set; }
        public string municipio { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> codigo_postal { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
