//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturafast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbr_Vendedor_Cliente
    {
        public int id_usuario_cliente { get; set; }
        public int id_vendedor_usuario { get; set; }
        public int id_cliente_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
